language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1
  - nightly
notifications:
    email:
    recipients:
      - nightly-dev@invenia.ca
    on_success: never
    on_failure: always
    if: type = cron
matrix:
  allow_failures:
  - julia: nightly
branches:
  only:
  - master
  - staging
  - trying
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+$/"  # Version tags
env:
  global:
  - secure: hW8qDovoCdn4+RVh2FLkU6BFYGpTzgvEkDLhnqFYAwXfrqN7VQGrVE64tJxJIN8GDZyJ+V7zj7xiIOVSmFMJwaHoEiXyQtCx7VmZrDoaBwL1QumMmC4YwvBZ5u2hdd3gghgYPofcRpbGQDIWs4PjAYu2NeMgZ3JQnnvScrjDlgqKF5dxJdzjrOy+rVOTSKm0kQm5MEJ2mQ9BLJcXGEur7YEPCPXHC4ClReYSnB8pGuKoAHztMhlWrfIcmaLSxNG/nCYjGHOhGeNZxRs0p0AUofq+Ef4SD+i+gC3SVHOJum2xJNnAmcqQe3V7D/1eIpOsPKK+DzT8ENr5icrVS76gxIClou/vhKMwl7syL9hsR54YO21icOUFbRSwUZWVn9xvDRXjTXYc5wTwjheqHbtwPjV6O5SHyNilerqijub3TCSc4U2y8+epDknn0a/rl18KWzjpBuKYozfCDwI8ugOGIqqVIl1XvdyFeQWawIUWthV1wxpvex7nhrxRI1nEjbF6YS7i3G/P9VIkhDNFqJmo6I5J9Aq228/gBaVRqdQOQ9dmXO13Jw6ZsiBAOeyDp8fTujF7b4EAEkcEFHW89kBlSMHhr+QMaVwK5jfjnJpqfiGs82P7mGPT1XllEkJu5SKIUiB7dO6dhkBLDUiArIt/ZDjeX60zckaAwqrepCwZ+zM=
  - secure: DGtg0N20c7smcOMGJlDk4Es+UH9/tGdqSbG3Quql+GgHgXT4PD3Rdua2AUj9keI4HL1TDX6sc0f/DRzoeSQ/t5bzcRoRjRAGIKR600blapzBAFoVXnRWZXFaiH07E2LkUyUyjM4NdTj7ZmZoaLeXRwMKs3wXCKcWemjgsXldEolqbgS9CEredYQLrNNqjRAdame6p2JeLhGclbHdgdIRuXwQkAxhfn1fHOGeOJ3PwQ2gKFTJ7ES6T5mcAa3Btc3XtRpLrwPkrQsedWZqWzKW0ENPVOmPOkY9qvB1HRZ/CR+DYyBcmLXbgHkkQ2Xa/GqNOe0HGO5Pm3ks9hLZa9GNyU2uw26uL2iPBwzixYGzSo1UJTq/JH3laN91vpFSKCJophmz90RFuYfnXWVB/dGC7Ag4Yq1o7NzZ3ymftXlVPHM+HVR/OkDe2KFOpHksjF8+O4NP9GdT6DoFLGrGCSfHkJSD3+gXwWY70i4R1VeVrlnFg8Z9zCvb+sV6WIkRSYt11MDdtrmze1N57RATpRiQ8XZ3PfSikBS8aWTZP048eEovS0Pzf+CKyjOfVox28dsRjAvkNeILJncUX+8ifPVUPgI5Ald+Hpi2gcSJqh44SS0rC4xRS5FW0tbaEXe01ndYfYbqM7l8h3mXAyzkLIMWw4VZxOMkK0YQyKfgdNfEXms=
