language: julia
os:
- linux
- osx
julia:
- 0.7
- 1.0
notifications:
  email: false
env:
  global:
  - secure: EzKnEeT2XFdzVVAvT9Qh0SKvXE74JmaP+wLd4YAt31n7midyt2Qdt/5sfnORqujKAcvJC3JcQPanzS3TBE/L9TFugrcr32gDwfkSHOKVmbd2RHlNt6qZprzBf0C9xhap8dnPjUUZdp65L5S4yzHbBLQc/I2skQpb2XQu0FetKhAt5hFn1bJ3KUJeBVsxQP78qt7o5bXbmkn5tU8Mqzk0EX4vCYjFAcnqoea9GUzbuGNt4bi09ckF+y6gtHRrUu9rpNZuKTB7upC2E9Z+nffrqZJCmm6ss94oqI9aySloAyETYbYMlBT3eUpulrumSrGzAAdXGywwKsQvcljj1+SW+Dz2d6o4nBMZOTjjdg0ss1+c4gCBMD2H1zkWEeRhMCidkzZBBUUwa/p5aUfSLehoZvVKFSTF0AGxKmbrjTrlqizM3R417UBSyQv5RE1e0JPMVcS8VZoso1uqmAM1LmkuuJv2KCfJ5/wBRVdQkheu5wOcpdtJkcmvhoy8OChpDQMvjcIbcXnw534qHdbpxRmW0sUOIt4RKeeZoLz/YoL1wg+kOCsvpssl4LUJu0TEYP0gDc5rAdANqUrfZ2u+NDA6jF4NVz+DuCADnzLFHmqCuyq3QwjdHuTM7hNaU5deF+bW4BS807o+4HJQHG08cD/rpizPL3ikot8p9CIX4ikxplY=
  - secure: ZFIclsDbXxzvhil6NDXz08ORTzxqtP2Dqvm0H1dlwfQKl6yXVDDoRJNskeyImjTGcgu5yZ18XTM0DkCaYz8BwTuYOAhvNCIQ3O/Qs26Pb2COfG8fmAeAlu8WL9eDih6d2lSUU6ACcIUF0+GJkPeVqi3GnFFisFYJyCdkh2Gv5HaQj+g2cK3aHnIHCe9nSMWLVh+/MqqWv0rUpXuwJPCSVtpZmj9a+jONsgXBj5LaTijRGeCGBUnbUuN5OjiVxJJN7KO6VTZAs+UkD1mFJ8ivBwnRSvkjkgsiEMtYeY+JmouNCJsdFkSu6TwsVw/DAhlsSd2SnYBQJCZNBPfwfoqseE7euViXv+zigfi8GC2YgJ5M0lZLJzRp/zBaIl8YtBmu09wQgw+wIP/fuEx3+4yWrDCIgPTqO+SINrUoNwUiVMfZevTpspCGJroOU3Al11WP2jI4W0KoqjTY9vMj+ZJzJJLxIlGCb+JK9NfMWnSZMx67nXh3VY+48w9Thi3fYSaq1In/H3nzbDiDwlnjDKKdxhYX6cOhlxMvSXNCrNnQEhzFAWdrlUrJPRgR4TkuHhO8BM1D52hdeu8PKx7Ovh3awdOFuPLgSIfCdQml9Izbdwtd/s1y9tR9ELFmIpIikQU82dkaPkMcTbpHl24RLS2pa9Jt1qAhfg/4raEExDS06BM=
matrix:
  allow_failures:
    - julia: nightly
